### ISSUE TITLE
Help doesn't work on decorated class (as opposed to instance) methods

### ISSUE THREAD

**Issue by davidhassell** [NCAS-CMS/cf-python#101]
For decorated class methods, the docstring is not printed by `help` when it is called in the class function, as opposed to the instance method:

```
>>> help(cf.Field.log)
Help on function log in module cf.decorators:

log(self, *args, **kwargs)

>>> help(cf.Field().log)  # Note () after Field
Help on method log in module cf.decorators:

log(*args, **kwargs) method of cf.field.Field instance
    The logarithm of the data array.
    
    By default the natural logarithm is taken, but any base may be
    specified.
<snip>
```
It's all ok for non-decorated methods:
```
>>> help(cf.Field.del_data)
Help on function del_data in module cfdm.core.abstract.propertiesdata:

del_data(self, default=ValueError())
    Remove the data.
    
<snip>
```

Is there a a way round this, so the docstring appears in all cases?

**Comment by sadielbartholomew** [comment]
I went to look into this, but I am afraid I can't re-create it. I just get the expected output, & similar results as expected for other (even multiply-) decorated methods, e.g:

```
>>> help(cf.Field.log)
Help on function log in module cf.mixin.propertiesdata:

log(self, base=None, inplace=False, i=False)
    The logarithm of the data array.
    
    By default the natural logarithm is taken, but any base may be
    specified.
    
    The "standard_name" and "long_name" properties are removed from
    the result.
    
    .. seealso:: `exp`
    
    :Parameters:
    
        base: number, optional
            The base of the logiarthm. By default a natural logiarithm
            is taken.
    
        inplace: `bool`, optional
...
...
...
>>> help(cf.Data.maximum)
Help on function maximum in module cf.data.data:

maximum(self, axes=None, squeeze=False, mtol=1, inplace=False, i=False, _preserve_partitions=False)
    Collapse axes with their maximum.
    
    Missing data array elements are omitted from the calculation.
    
    .. seealso:: `minimum`, `mean`, `mid_range`, `sum`, `sd`, `var`
    
    :Parameters:
    
        axes : (sequence of) int, optional
    
        squeeze : bool, optional
...
...
...
```

Am I missing something? Or, is there perhaps something environment-specific causing this?

**Comment by davidhassell** [comment]
OK - I'll double check ...

**Comment by davidhassell** [comment]
Hi @sadielbartholomew, it is still a problem for me running from the master branch of this repo. Is that where you are running from?

**Comment by sadielbartholomew** [comment]
Yes, that was on master. I've double checked & I still see as I saw before. For me a pip install of ``3.5.1`` also gives the right behaviour.

There may be a Python version dependence issue behind the differences we are seeing. Which were you using? I was using ``3.7.6``.

I think the key is with ``functool.wraps`` which is designed to manage docstrings etc. appropriately for decorated functions. Use of wraps is all standard and fine for singly-nested wrapper functions in decorators, but I think the issue may be that the specific decorator for  ``Field.log`` is ``_deprecated_kwarg_check()``, which takes arguments and therefore needs two nested wrapper functions:

https://github.com/NCAS-CMS/cf-python/blob/ce86f3e81596d83e46da0f591accf9c28b20ac19/cf/decorators.py#L23-L40

and so, despite use of ``@wraps()`` there is still issue due to the nesting. Adding another ``@wraps()`` on the outer level won't help.

Looking around, I think there may be fundamental problems in trying to access the ``help`` utility for such nested decorators. But I suspect they could possibly be resolved by use of [``functools.update_wrapper``](https://docs.python.org/3/library/functools.html#functools.update_wrapper) somewhere.

I am thinking that if the nesting is the problem, I can reformulate that decorator according to the [approach outlined under 'Adding Variables To The Decorator' in this blog post](https://timber.io/blog/decorators-in-python/) which logically seems like it should work. I think it is also possible to reformulate using ``functools.partial`` to avoid nested wrappers.

Since I can't recreate it to test, can I suggest you first check to see if the problem occurs for any decorator, or just that nested one, to see if the problem can be narrowed down to certain decorator cases.

 BTW, some good reference I found while looking into it, in case you have time to look into it, are:
* https://hynek.me/articles/decorators/
* https://stackoverflow.com/questions/39256072/applying-functools-wraps-to-nested-wrappers

**Comment by davidhassell** [comment]
Thanks for the background. I am using Python 3.7.0. I shall try with 3.7.6 (or newer). I think that there is no need to refactor if a newer python magically fixes the problem.

**Comment by davidhassell** [comment]
OK - stop press - it's working for me a t Python 3.7.0, now! This could be the ghost in the (well, my) machine. I'll close this for now, but we can reopen the issue if it comes back ...

**Comment by sadielbartholomew** [comment]
> OK - stop press - it's working for me a t Python 3.7.0, now! This could be the ghost in the (well, my) machine.

Bizarre!

> I'll close this for now, but we can reopen the issue if it comes back ...

That sounds good to me. And if not, we can simply blame that new release of Linux Mint you are using :smile:

I was actually wondering if there was something really weird happening with conda, since my cf-python version seemed to be oscillating every ~5 seconds (& plain wrong on one of the sides, as `3.6.0` was my dev version...)! I copied & pasted it since it was so strange (see below). So my wild theory of the day/week is that through conda issues you were in fact using Python <=3.4 despite being told otherwise.

```console
(base)  :( [sades@03:49 pm]cf> pip install cf-python==3.5.1
Collecting cf-python==3.5.1
  Downloading cf-python-3.5.1.tar.gz (1.5 MB)
     |████████████████████████████████| 1.5 MB 1.7 MB/s 
Requirement already satisfied: netCDF4>=1.5.3 in /home/sadie/anaconda3/lib/python3.7/site-packages (from cf-python==3.5.1) (1.5.3)
Requirement already satisfied: cftime>=1.1.3 in /home/sadie/anaconda3/lib/python3.7/site-packages (from cf-python==3.5.1) (1.1.3)
Requirement already satisfied: numpy>=1.15 in /home/sadie/anaconda3/lib/python3.7/site-packages (from cf-python==3.5.1) (1.18.1)
Requirement already satisfied: cfdm<1.9,>=1.8.5 in /home/sadie/cfdm (from cf-python==3.5.1) (1.8.6)
Requirement already satisfied: psutil>=0.6.0 in /home/sadie/anaconda3/lib/python3.7/site-packages (from cf-python==3.5.1) (5.7.0)
Requirement already satisfied: cfunits>=3.2.7 in /home/sadie/cfunits (from cf-python==3.5.1) (3.2.8)
Requirement already satisfied: future>=0.16.0 in /home/sadie/anaconda3/lib/python3.7/site-packages (from cfdm<1.9,>=1.8.5->cf-python==3.5.1) (0.18.2)
Requirement already satisfied: netcdf_flattener>=1.0.1 in /home/sadie/anaconda3/lib/python3.7/site-packages (from cfdm<1.9,>=1.8.5->cf-python==3.5.1) (1.0.1)
Building wheels for collected packages: cf-python
  Building wheel for cf-python (setup.py) ... done
  Created wheel for cf-python: filename=cf_python-3.5.1-py3-none-any.whl size=1792363 sha256=3ae1edb75f51d90d11f799769905da3675ffc6e5f679464ca7d05ea46f8f3894
  Stored in directory: /home/sadie/.cache/pip/wheels/6c/e5/d1/dd34068d50c0bfa379fe430af449eae71819dff64f69315868
Successfully built cf-python
Installing collected packages: cf-python
  Attempting uninstall: cf-python
    Found existing installation: cf-python 3.4.0
    Uninstalling cf-python-3.4.0:
      Successfully uninstalled cf-python-3.4.0
Successfully installed cf-python-3.5.1
(base)  :) [sades@03:50 pm]cf> conda list | grep cf-python
cf-python                 3.4.0                     dev_0    <develop>
(base)  :) [sades@03:50 pm]cf> conda list | grep cf-python
cf-python                 3.5.1                    pypi_0    pypi
(base)  :) [sades@03:50 pm]cf> conda list | grep cf-python
cf-python                 3.4.0                     dev_0    <develop>
(base)  :) [sades@03:50 pm]cf> conda list | grep cf-python
cf-python                 3.4.0                     dev_0    <develop>
(base)  :) [sades@03:50 pm]cf> conda list | grep cf-python
cf-python                 3.5.1                    pypi_0    pypi
(base)  :) [sades@03:50 pm]cf> conda list | grep cf-python
cf-python                 3.4.0                     dev_0    <develop>
(base)  :) [sades@03:50 pm]cf> conda list | grep cf-python
cf-python                 3.5.1                    pypi_0    pypi
```
