### ISSUE TITLE
DeprecationError in aggregate with relaxed_identities

### ISSUE THREAD

**Issue by m-couldrey** [NCAS-CMS/cf-python#188]
Hi, thanks in advance for any help with this.

I'm using cf.aggregate to try and aggregate together output from different models along their source dimension. In previous versions of cf, this command worked:
agf = cf.aggregate(fl, dimension=('source', ),relaxed_identities=True,verbose=verblev)
where fl is a fieldlist and all members have a property called 'source' set to a model name and verblev is 1. The fields in fl all have X Y and Z axes. 

When I run the command (in cf 3.8.0 but also 3.7.0) I get a deprecation error; it looks like aggregate uses a deprecated option:
8/.local/lib/python3.7/site-packages/cf/aggregate.py", line 1713, in aggregate
    respect_valid=respect_valid)
  File "/home/users/mpc18/.local/lib/python3.7/site-packages/cf/aggregate.py", line 417, in __init__
    f.axis_name(axis))
  File "/home/users/mpc18/.local/lib/python3.7/site-packages/cf/field.py", line 20528, in axis_name
    "Use 'domain_axis_identity' method instead."
  File "/home/users/mpc18/.local/lib/python3.7/site-packages/cf/functions.py", line 3472, in _DEPRECATION_ERROR_METHOD
    message
cf.functions.DeprecationError: Field method 'axis_name' has been deprecated at version 3.0.0 and is no longer available. Use 'domain_axis_identity' method instead.

The environment info is as follows:
>>> cf.environment(paths=False)
Platform: Linux-3.10.0-1127.19.1.el7.x86_64-x86_64-with-centos-7.8.2003-Core
HDF5 library: 1.10.5
netcdf library: 4.7.3
udunits2 library: /home/users/mpc18/miniconda3/lib/libudunits2.so.0
Python: 3.7.4
netCDF4: 1.5.3
cftime: 1.3.0
numpy: 1.18.1
psutil: 5.7.0
scipy: 1.4.1
matplotlib: 3.1.3
ESMF: 8.0.0
cfdm: 1.8.8.0
cfunits: 3.3.1
cfplot: 3.0.5
cf: 3.8.0

Cheers!
Matt

**Comment by sadielbartholomew** [comment]
Hi Matt @m-couldrey, thanks for opening an issue and providing the details for us.

Indeed having checked the codebase there is an under-the-hood use of the deprecated method `axis_name` which has caused the bug you report, so thanks for alerting us to it.

It is still present in the `master` branch so I will fix it to use the newer method to remove the bug for the next version. We are hoping to do a new release next week (perhaps even tomorrow though that is looking more unlikely now).

The particular offending usage was in message designed to be sent to the log, though because the message is stored in an instance variable then passed through, adjusting the verbosity won't prevent it from being called in otherwise the same circumstances you ran into:

https://github.com/NCAS-CMS/cf-python/blob/677b04a1d98d50b1abd9941b8be3ebe7fe4d589e/cf/aggregate.py#L432-L444

Unfortunately this means I can't think of a simple workaround for 3.8.0 to avoid the bug; the logic implies that ensuring all axes have a canonical identity set would avoid the deprecated call and hence the bug, but doing that obviously defeats the point of using `relaxed_identities`.

Are working via the RACC or JASMIN? If so we can do a custom patch on 3.8.0 for you to apply the one-line fix if it would be helpful so you can avoid the bug whilst still using 3.8.0. Or is it not too much trouble to avoid using `relaxed_identities` on those particular dataset(s) for a week or so when we will have the new release out?

**Comment by m-couldrey** [comment]
Thanks for looking into this promptly @sadielbartholomew 

I managed to find a workaround (which is along the lines you suggest) that didn't involve using relaxed_identities=True so this isn't an issue for me any more. It's possible that since other parts of my code use the flag, that the issue will recur for me at some point. I think if that happens, it'll probably be sometime when I'll be using a future release. If not, I could just try switching the method to the current one and see if that works. So I should be fine to wait until the next release!
