### ISSUE TITLE
losing track of source files after equality comparisons

### ISSUE THREAD

**Issue by ThibHlln** [NCAS-CMS/cf-python#211]
Hi,

I am experiencing a behaviour that I cannot understand.

In the script below, I am spatially comparing two fields, by comparing their X/Y/Z dimension coordinates separately (files containing these fields available in [Archive.zip](https://github.com/NCAS-CMS/cf-python/files/6460021/Archive.zip)).

In the process of doing so, I seem to be losing the reference to the original data file, see `field2.get_filenames()` before and after the `for` loop.

```python
import cf
import re

fld1 = cf.read('spacedomain.nc')[0]

fld2 = cf.read('data.nc', select='ancillary_c')[0]
arr2 = fld2.array

print(fld2.get_filenames())

# check whether they are spatially equivalent _________________________________

x_y_z = []

for dim_name in ['longitude', 'latitude', 'altitude']:

    dim_coord = fld2.dim(re.compile(r'name={}$'.format(dim_name)))

    # drop all properties but 'units' for comparison
    properties = list(dim_coord.properties())
    try:
        properties.remove('units')
    except ValueError:
        pass

    x_y_z.append(
        fld1.dim(dim_name).equals(
            dim_coord,
            rtol=1e-5, atol=1e-8,
            ignore_data_type=True,
            ignore_fill_value=True,
            ignore_properties=properties
        )
    )

x_y_z = all(x_y_z)

# _____________________________________________________________________________

print(fld2.get_filenames())
```

Now, here are three changes I found that would allow me to retain the reference to the data file:
1. removing `arr2 = fld2.array`
2. removing `ignored_properties=properties`
3. removing any 1 of the 3 items in the list `['longitude', 'latitude', 'altitude']`

I don't really understand why any of these three changes have an impact on what `get_filenames()` returns.

It may be useful to mention that *data.nc* in [Archive.zip](https://github.com/NCAS-CMS/cf-python/files/6460021/Archive.zip) contains other fields, e.g. 'driving_a', and if one uses it in place of 'ancillary_c', the problem disappears. The main difference between 'ancillary_c' and 'driving_a', is that the latter has a 'time' dimension, while the former does not. So this may explain 3. (i.e. if all dimensions are checked, the reference is dropped somehow?).

Can anyone reproduce this? How could I avoid this behaviour without resorting to 1. 2. or 3.?

> Platform: macOS-10.16-x86_64-i386-64bit 
HDF5 library: 1.10.6 
netcdf library: 4.7.4 
udunits2 library: /bin/../lib/libudunits2.dylib 
Python: 3.8.5
netCDF4: 1.5.5.1
cftime: 1.3.1
numpy: 1.19.5
psutil: 5.8.0
scipy: 1.6.0
matplotlib: 3.3.3
ESMF: 8.0.1
cfdm: 1.8.8.0
cfunits: 3.3.1
cfplot: 3.0.38
cf: 3.8.0

**Comment by davidhassell** [comment]
Hi Thibault,

Thanks for the detailed description - very helpful to work out what is going on. I think you have come across a "feature".

Every time you access data on disk, cf-python sees if it can keep it in memory, rather than as a file pointer, and if it can then it forgets the file pointer completely. In your script, data access happens in the `arr2 = fld2.array` line and the `equals` calls.

Your differential diagnoses had the effect of short-circuiting the `equals` calls before they got to the (expensive) data comparison, thereby retaining thereby data as file pointer which can be reported in by `get_filenames`. You could get a similar effect by removing line `arr2 = fld2.array` or `ignore_properties=properties`.

So, if you want the filenames robustly, the answer is probably to get them after reading, but  before and manipulations that _might_ touch the data.

I hope that that's OK and makes sense,
David

**Comment by ThibHlln** [comment]
Hi David,

Thank you for your quick and detailed reply.

I think I understand the reasoning behind forgetting about the file pointer if data is accessed and fits in memory. So I understand why 1. has the effect of losing the file reference. I'm glad I've learnt this today. 🙂 

However, I don't understand why `ignore_properties=properties` or reducing the number of dimension coordinates checked is short-circuiting the `equals`, because data will still be need to be on disk at some point?

Thank you for the tip, I will store the file references early on in my workflow to make sure I don't lose them then.

**Comment by davidhassell** [comment]
Hi Thibault,

It's only the data arrays that remain on disk as file pointer, the metadata properties (standard_name, long_name, etc.) are read into memory during `cf.read`. So, the `equals` method checks the properties first, which is very fast because they're always in memory, and if any are different it can return `False` without the need to read the data from disk.

**Comment by ThibHlln** [comment]
Ha, of course. Silly me. Now I understand! Thank you again David. I will let you close this issue

**Comment by davidhassell** [comment]
Thanks Thibault - keep the questions coming!
