### ISSUE TITLE
UGRID support?

### ISSUE THREAD

**Issue by jveeramon** [NCAS-CMS/cf-python#214]
Does cf support UGrid convention? I am trying to regrid data from a UGrid to a structured grid. Here is what my field looks like:

In [3]: print(f)
Field: sea_surface_height (ncvar%mesh2d_s1)
-------------------------------------------
Data            : sea_surface_height(time(193), ncdim%mesh2d_nFaces(285665)) m
Cell methods    : ncdim%mesh2d_nFaces(285665): mean
Dimension coords: time(193) = [2018-10-07 18:00:00, ..., 2018-10-11 18:00:00]
Auxiliary coords: longitude(ncdim%mesh2d_nFaces(285665)) = [-83.24000000000001, ..., -87.38800000000002] degrees_east
                : latitude(ncdim%mesh2d_nFaces(285665)) = [30.191999984826857, ..., 30.62799975515764] degrees_north
Cell measures   : measure:area(ncdim%mesh2d_nFaces(285665)) = [171375.81883366389, ..., 2729793.5635016114] m2
Coord references: grid_mapping_name:latitude_longitude

**Comment by sadielbartholomew** [comment]
Hi, sorry cf-python does not _currently_ support UGRID because the CF Conventions do not presently and formally include support for UGRID as a complementary standard. However, this is likely to change in the future because there are long-standing plans to unite the URGID (and SGRID) Conventions with the CF Conventions by tying given versions of each together (for more detail, please consult for example [the proposal with discussion for tying UGRID and CF together from the CF Conventions perspective](https://github.com/cf-convention/cf-conventions/issues/153)). If (but probably 'when') CF officially supports UGRID, the CF data model will be required too, so corresponding versions of cf-python, via its dependency cfdm, will do too.

As for the field in question you have referenced with a UGRID, I don't think there is a way at present to manipulate the UGRID mesh so it can be regridded. @davidhassell will know for sure...

**Comment by davidhassell** [comment]
Hi - UGRID will finally be in CF-1.11 (released December 2023), and cf-python v3.16.0 will have UGRID support for everything _except_ writing to netCDF files. I.e. it will support reading, collapsing, _**regridding**_, arithmetic, etc. cf-plot will also be updated.

cf-python v3.16.0 will also be released in December 2023
