### ISSUE TITLE
New differential operators: Laplacian, grad, div and curl

### ISSUE THREAD

**Issue by davidhassell** [NCAS-CMS/cf-python#292]
Being able to calculate the differential operators [Laplacian](https://en.wikipedia.org/wiki/Laplace_operator), [div](https://en.wikipedia.org/wiki/Divergence) (divergence of a vector of fields), [grad](https://en.wikipedia.org/wiki/Gradient) (vector derivative of a scalar field), and [curl](https://en.wikipedia.org/wiki/Curl_(mathematics)) on field constructs would be useful, preserving metadata through the operations and setting the correct units.

The current use case (towards calculating the baroclinic geostrophic part of ocean dynamic sea level from the density field) is for calculating these quantities on the horizontal X-Y plane, either in Cartesian coordinates (e.g. plane projections), or in spherical polar coordinates. In the latter case the plane is the theta-phi plane for a constant radial distance to the origin.

I propose the following methods and syntax:

```python
>>> f = cf.example_field(0)
>>> lp = f.laplacian_xy()
>>> fx, fy = f.grad_xy()
>>> d = cf.div_xy(fx, fy)
>>> c = cf.curl_xy(fx, fy)
```
In the spherical polar case, it will be assumed that the inferred or provided radius is applicable at all horizontal locations, and to all vertical levels. An extension to allow for varying Z on each X-Y plane should be possible, if desired.

**Comment by sadielbartholomew** [comment]
Sounds like a very useful enhancement. I am happy with the method name and syntax proposed, it seems the most logical in context.

I was just wondering if this simplifies or could even could mop up (say, with some basic follow-on work) some other open issues, namely https://github.com/NCAS-CMS/cf-python/issues/36 and https://github.com/NCAS-CMS/cf-python/issues/178? Notably it looks like this might be solving #178 directly, unless I am missing something?

Will review your PR for this issue shortly. (It would be useful if we could review priorities via Slack though, as there are some other PRs I am due to review, including a large one, and not sure which is most pressing...)

**Comment by davidhassell** [comment]
Hi Sadie - thanks. Well remembered about those older issues. This PR will indeed also close #178. As for vorticity, we should, in another issue, think about implementing a 2-d curl operator and take #36 from there (and probably rewrite `cf.relative_vorticity` in the process).

**Comment by davidhassell** [comment]
Decide to add curl in now, whilst it's all in mind  - have updated the title and first post.

**Comment by JonathanGregory** [comment]
Dear @davidhassell 

Thanks very much. This looks like just what we need.

Best wishes

Jonathan
