### ISSUE TITLE
Truncated units when reading in um files for water_sublimation_flux (ncvar%m01s03i298)

### ISSUE THREAD

**Issue by dlrhodson** [NCAS-CMS/cf-python#444]
Hi again Both!

  Slightly specific bug that I have been unable to track down.
  I have a UM file that contains the field 03298 - it should have the units `kg m-2 s-1` - if I read this in using `cf.read()` it returns units of `kg m-2 s-` ie the '1' is truncated for some reason. It ONLY happens with the 03298 field. This made me think there must be an error in the `cf/etc/STASH_to_CF.txt` file  but it seems not:

```
1!3298!SUBLIM. SURFACE (GBM) : RATE KG/M2/S!kg m-2 s-1!405!407!water_sublimation_flux!!
1!3298!SUBLIM. SURFACE (GBM) : RATE KG/M2/S!kg m-2 s-1!503!!water_sublimation_flux!!

```
I can get around this - but it matters because `cf.aggregation()` fails when the units are `kg m-2 s-` ! So a `cf.read() ` on a  list of  UM files that contain this field will fail, because the aggregation fails!

See attached code for replication (using `3.10.0`) (`test_data.nc` was too big to attach - but can be found here `/home/users/dlrhodso/CANARI/monitoring/test_data.nc` )

Cheers, 
Dan

![image](https://user-images.githubusercontent.com/11614821/188190408-c2a4c02e-764d-4626-9689-5cd6ff6f9806.png)

[example.py.gz](https://github.com/NCAS-CMS/cf-python/files/9479225/example.py.gz)

**Comment by sadielbartholomew** [comment]
Hi @dlrhodson, thanks so much for raising this, especially for including a lot of detail and an example script. That is indeed clearly a bug!

Apologies also for the lateness of reply, due to both David and myself being pre-occupied with some workshops and similar events over the last weeks.

l will have a look shortly and report back here (David is on leave at the moment, but I hopefully should be able to work out what is going on here myself) and then I can make a fix for you.

One question: it wasn't clear from:

> I can get around this - but it matters because cf.aggregation() fails when the units are kg m-2 s- ! So a cf.read() on a list of UM files that contain this field will fail, because the aggregation fails!

whether you have a workaround or not (the first statement implies you do, but the rest of the statement might contradict that)? If you don't, do let us know here so I can advise regarding that, also.

**Comment by dlrhodson** [comment]
Hi @sadielbartholomew  - no problem at all! It's not a major bug - just a weird one!

Apologies for not being clear! I **do** have a work around. 
This is -  rather than `cf.read('*.nc') ` I do a `files=glob.glob('*.nc')` then 
```
for file in files: 
  data=cf.read(file)

```
I can then check for bad units for each file, patch any units that are bad, then aggregate everything at the end.
This works, but clearly isn't what cf should do! It will break cf.read() for a very (very) small subset of users.

I mostly highlighted it because, although it is a low priority bug to fix, I cannot understand why it should happen for this particular diagnostic alone - so just in case there is a deeper issue here!

**Comment by sadielbartholomew** [comment]
Thanks for the quick response!

> Apologies for not being clear! I do have a work around.

No apologies required, it was probably clear generally but I wanted to be sure. Glad you have a workaround; the one you state is very sensible and what we would have suggested to do. But I agree, it shouldn't be necessary. 

Though you point out that the aspect you've run into isn't 'major' in itself, I think you've hit the nail on the head with:

> I cannot understand why it should happen for this particular diagnostic alone - so just in case there is a deeper issue here!

because the bug almost certainly applies in a more general case as you realise (we don't hard-code anything against particular diagnostics, for example), we just need to work out what that is and why, so we can fix it. I certainly wouldn't class this as low priority in that respect - all bug fixes are higher priority than. say, enhancements, in my view.


Anyway, I should have time to look at this later today so will let you know what I deduce. I should add that this relates to units so may, depending on where the issue lies, actually be a bug in the library we use to deal with the units under-the-hood in `cf`, [`cfunits`](https://github.com/NCAS-CMS/cfunits), rather than `cf` itself. I will transfer this issue across to that repository if it becomes clear that it is `cfunits` at fault here.

**Comment by sadielbartholomew** [comment]
Hi Dan, sorry I am only just getting a chance to look at this now (due to priorities). Just one quick thing, it would be useful for me to use the file you mention for debugging, but I am not sure which location / filesystem you are pointing to here, since the path could apply in many cases I know of:

> test_data.nc was too big to attach - but can be found here `/home/users/dlrhodso/CANARI/monitoring/test_data.nc`

Having briefly asked around in the office we think JASMIN is most likely, is that right? (If you can't reply today I'll probably login and check on JASMIN myself, but in case you are online and can let me know!) Thanks.

**Comment by dlrhodson** [comment]
Yes - JASMIN - sorry I wasn't very clear! Let me know if you can't see it. I can try to extract the problem diagnostic and put it into a smaller file if this will help!

**Comment by sadielbartholomew** [comment]
Thanks Dan, I'll grab it now from JASMIN.

**Comment by sadielbartholomew** [comment]
Hi Dan, sorry I am getting a 'Permission denied' on the whole `monitoring` directory. Please can you either make it read-able to me via permission changes, or move the `test_data.nc` file elsewhere (I'm `slb93` on JASMIN if you wanted to move it into my root user directory if that's possible).

**Comment by dlrhodson** [comment]
Sorry! I don't have permissions to see ~slb93/ , but can you see `/home/users/dlrhodso/test_data.nc` ?

**Comment by sadielbartholomew** [comment]
To add, I think the reason I can't access it is (based on looking at some sym-links you've got there) it is under `/gws/nopw/j04/canari/users/dlrhodso` and I don't think I have JASMIN services access to that.

**Comment by dlrhodson** [comment]
Ah yes - sorry, I forgot I was linking to the GWS!

**Comment by sadielbartholomew** [comment]
No problems, I've actually managed to grab the file because there was one with the same name in your user root directory so I thought I'd try a `scp` on that and it gives the same errors as above with your example script therefore looks like the right one. So I have it now, thanks, and no need to do anything further!

**Comment by dlrhodson** [comment]
Oh, goodness - apologies - my error! This is model output from the UM - the UM usually outputs .pp, but Jeff has implemented a cf netcdf conversion so that the model outputs netcdf, and we are trying it out.
I had assumed that cf-python reads in the stash code variable name and used this to map the variable units, but now, after you pointed it out, it's obviously the error is there in the original netcdf output by the model! Not sure how I missed that! So the problem must be upstream with Jeff's units mapping table when he does the conversion to netcdf. I will take this up with Jeff!
Apologies for taking up your time, but thanks for finding my error!
