### ISSUE TITLE
Doing the 30 minute tutorial dies with deprecation errors

### ISSUE THREAD

**Issue by aklgil** [NCAS-CMS/cf-python#655]
Ran the command 

```
regridded_precip_field = precip_field.regrids({'longitude': lon, 'latitude': lat}, method='conservative')
print(regridded_precip_field) 
```

as part of the 30 minute tutorial which I cloned from

> git clone https://github.com/NCAS-CMS/cf-tools-training.git

**Comment by aklgil** [comment]
Whoops. Actually more errors early ... KeyError in the seasons section ...

**Comment by davidhassell** [comment]
Hi @aklgil,

Thanks for letting us know. Could you please raise this as an issue over at https://github.com/NCAS-CMS/cf-tools-training (mentioning exactly which cell of which notebook it came from), as this is most likely a problem of the example code not having been updated for the newest version of cf-python, rather than a problem with cf-python itself.

Many thanks,
David
